### ISSUE TITLE
Mixed content on poul.org

### ISSUE THREAD

**Issue by pogliamarci** [Politecnico-Open-unix-Labs/hipoul#3]
On the poul website, served over https, there is a reference to http://www.poul.org/wp-content/themes/hipoul/js/bits.js. This is a script, and gets (rightfully) blocked by any decent browser.

This might be caused by get_template_directory_uri() returning an HTTP uri in hipoul/footer.php.

Same for newlogo.svg being requested over http and causing a mixed content warning, that may be caused by bloginfo('template_directory'); returning an HTTP URI in front-page.php, and for the target of the search form (http://www.poul.org).

In general various links on poul.org are http link instead of https link (e.g. link to the mailman page on the footer). Better to omit the scheme from the uri (//whatever/whatever.htm) if possible when linking to other poul.org pages so that https is preserved when used.

**Comment by pogliamarci** [comment]
Some pages triggering mixed content issues:
- https://www.poul.org/
- https://www.poul.org/2014/12/conferenza-privacy-sicurezza-2015/ 
- https://www.poul.org/?s=prova

Other pages do not trigger mixed content issues, and they pull the correct (https) .js and logo from the template.

**Comment by esseks** [comment]
That's a somewhat idiotic issue with WordPress (no blame on @ff- :smile: ) due to the use of absolute URLs. Maybe some SSL plugin can solve it.

**Comment by esseks** [comment]
That was a somewhat idiotic issue on the part of WordPress due to their use of absolute URLs vs relative. Fixed in the WP config, please confirm @pogliamarci.

**Comment by pogliamarci** [comment]
@esseks I still get mixed content warning on https://www.poul.org/

**Comment by esseks** [comment]
@pogliamarci  I don't, try reloading a few times and/or flushing the cache.

**Comment by pogliamarci** [comment]
$ curl https://www.poul.org
[...]
[<]script src="http://www.poul.org/wp-content/themes/hipoul/js/bits.js"></script>

$ curl https://www.poul.org/events/
[...]
[<]script src="https://www.poul.org/wp-content/themes/hipoul/js/bits.js"></script>

**Comment by esseks** [comment]
`curl https://www.poul.org/events | fgrep http:` returns nothing here and I get no "mixed content" warning in browser. Please check again.

**Comment by pogliamarci** [comment]
On 31/03/15 15:13, Stefano Sanfilippo wrote:

> |curl https://www.poul.org/events | fgrep http:| returns nothing here,
> that's a weird issue. Please check again.

Yeah, its part of the issue indeed.

/events does not show mixed content

/ shows mixed content

**Comment by esseks** [comment]
Reopening until the issue is debugged. The issue appears to be Firefox-specific, @pogliamarci can you confirm? Please check if Chrome/Chromium works or not.

**Comment by pogliamarci** [comment]
On 31/03/15 15:24, Stefano Sanfilippo wrote:

> This issue appears to be Firefox-specific, can you confirm this? Also,
> check if Chrome/Chromium works or not.

In can confirm the issue using Chrome 27 on a CentOS6 system where the
poul.org website was _never_ opened before.
- poul.org redirects to http://www.poul.org (plain HTTP) the first time
  it is accessed (think it is a misconfiguration because
  https://www.poul.org contains the HSTS header so it's supposed to be
  used over https only)
- https://www.poul.org triggers mixed content (at least on the homepage
  and on the search result page, not on the internal pages such as /events).

**Comment by pogliamarci** [comment]
![screen shot 2015-03-31 at 15 31 54](https://cloud.githubusercontent.com/assets/1477884/6919956/730297f6-d7bb-11e4-9434-7f4d871c6e5e.png)
Attached screenshot of Chrome displaying the mixed content warning on the console.

**Comment by esseks** [comment]
Turns out it was really a cache problem. Closing, for the last time, hopefully :)

**Comment by f-f** [comment]
I'm reopening it because I still have the mixed content warning. Investigating - a quick fix could be to hardcode the problematic urls.

**Comment by pogliamarci** [comment]
This seems to happen every time someone visits poul.org over http.
I used curl to retrieve http://www.poul.org/events, and now https://www.poul.org/events triggers the mixed content warning.

**Comment by f-f** [comment]
So the issue seems to be the caching plugin.

**Comment by esseks** [comment]
Seems like forcing a HTTPS connection to the website in the server config solves the caching issue.
